server:
  host: HOST
  port: PORT
  domain: DOMAIN

env:
  environment: ENVIRONMENT
  logLevel: LOG_LEVEL
  name: npm_package_name
  version: npm_package_version

secret: SECRET

db:
  client: DB_CLIENT
  connection: DB_CONNECTION
